= lab 4

. По полученному базовому классу (из предыдущей лабораторной работы) создать
  классы наследников по двум разным ветвям наследования (B←P1←P11 и B←P2←P21):
** во всех классах должны быть свои данные (характеристики объектов);
** во всех классах создать конструкторы инициализации объектов для всех классов
   (не забыть про передачу параметров в конструкции базовых классов);
**  остальные методы создавать по необходимости.
. Создать в базовом классе виртуальные функции расчета (например, расчет площади
  фигуры и т.п.) и вывода объекта на экран (всех его параметров). Выполнить
  реализацию этих виртуальных функций в классах наследниках.
. В классе контейнере создать массив, состоящий из объектов базового класса.
  Заполнить массив динамически создаваемыми объектами производных классов (P1,
  P11, P2, P21). Для каждого элемента массива проверить работу виртуальных
  функций.
. Отладить и выполнить полученную программу. Проверить, что будет, если
  вышеописанные методы не будут виртуальными.
