= lab 6

. Для созданного в предыдущей лабораторной работе контейнерного класса
  реализовать методы, которые в качестве аргумента принимают делегат:
** метод сортировки;
** метод поиска;
** метод фильтрации.
. Для каждого делегата определить один метод и одно лямбда-выражение.
. Коллекция изменяется при удалении/добавлении элементов или при изменении одной
  из входящих в коллекцию ссылок, например, когда одной из ссылок присваивается
  новое значение. В этом случае в соответствующих методах или свойствах класса
  бросаются события.
. При изменении данных объектов, ссылки на которые входят в коллекцию, значения
  самих ссылок не изменяются. Этот тип изменений непорождает событий. Для
  событий, извещающих об изменениях в коллекции, определяется свой делегат.
  События регистрируются в специальных классах-слушателях.
. Для событий предусмотреть возможность подписки и отписки отсобытия.
. Для обработки всех ошибочных ситуаций использовать конструкцию try...catch().
. В Main создать два экземпляра шаблонного класса-контейнера для разных типов
  данных. Работа с этими объектами должна демонстрироваться на следующих
  операциях:
** добавить;
** просмотреть;
** найти;
** удалить;
** найти;
** просмотреть.
. Отладить и выполнить полученную программу. Проверить обработку исключительных
  ситуаций (например, чтение из пустого стека, дублирование объектов и т.п.).
