= lab 10

. Создайте в среде разработки MS VS проект. В качестве типа проекта
  выбрать "Windows Application" (или "Windows Forms Application" в зависимости
  от версии .NET Framework).

. После создания и сохранения проекта измените программу таким образом,
  чтобы координаты курсора мыши выводились в заголовке главного окна приложения.

. Добавьте текстовое поле (TextBox) в режиме разработки (для этого
  необходимо использовать панель элементов управления "ToolBox"). Дополните
  обработчик движения мыши таким образом, чтобы в текстовом поле отображалась
  сумма координат указателя мыши.

. Работающую программу необходимо представить преподавателю.

. После этого выполните индивидуальное задание в соответствие с
  вариантом. В каждом задании необходимо вывести значение выражения,
  предварительно введя значения переменных в соответствующие текстовые поля
  формы главного окна приложения. Результат выводится в заголовок окна в ответ
  на нажатие кнопки (кнопку также необходимо поместить на форму).

. Для выполнения индивидуального задания необходимо использовать
  математические функции, которые доступны в виде статических методов класса
  Math.
